language: ruby

sudo: false

rvm:
  - 2.2.4

bundler_args: --without development --jobs=9 --retry=2 --quiet

before_script:
  - cp config/config.yml.sample config/config.yml
  - cp config/database.yml.sample config/database.yml

script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
  - bundle exec rake cucumber
