- https://github.com/adamtanner/*
- https://github.com/f-list/*
- https://github.com/gae-init/gae-init
- https://github.com/ggreer/the_silver_searcher
- https://github.com/iros/*
- https://github.com/jsocol/*
- https://github.com/libretro/*
- https://github.com/lipis/*
- https://github.com/meowy/*
- https://github.com/misoproject/*
- https://github.com/mitsuhiko/*
- https://github.com/mplewis/*
- https://github.com/sczizzo/*
- https://github.com/tcrayford/*
- https://github.com/untitaker/*
- https://github.com/joomla/*
- https://github.com/lavagetto/*
- https://github.com/jplana/python-etcd
- https://github.com/sitaramc/*
- https://github.com/gitolite/*
- https://github.com/MarkusH/*
- https://github.com/titanous/*
- https://github.com/flynn/*
- https://github.com/mbabker/*
- https://github.com/BabDev/*
- https://github.com/joomla-framework/*
- https://github.com/joomla-extensions/*
- https://github.com/joomla-projects/*
- https://github.com/ForumPostAssistant/FPA
- https://github.com/ipython/*
- https://github.com/mpasternacki/*
- https://github.com/3ofcoins/*
- https://github.com/ggventurini/python-deltasigma
- https://github.com/SirCmpwn/*
- https://github.com/MediaCrush/*
- https://github.com/KnightOS/*
- https://github.com/KerbalStuff/*
